"""scripts/check_doc_counts.py, the documentation's release-time checks.

No gate compares two hand-written copies of a count: TESTING.md's status is
generated by scripts/render_status.py (tests/test_render_status.py), and
this script asks, at release, whether it is what that script writes now.
Release mode is chosen from the version bump (#1536), and ``--print-release-
mode`` answers the same question for ci.yml's plan job.  The one check that
needs the GitHub API, KNOWN_ISSUES.md's Bugs table against the open
`bug`-labelled issues, is opt-in.
"""

from __future__ import annotations

import importlib.util
import os
import re
import subprocess
import sys
import types
from pathlib import Path
from typing import Any

import pytest

_SCRIPT = Path(__file__).parent.parent / "scripts" / "check_doc_counts.py"


def _load() -> Any:
    spec = importlib.util.spec_from_file_location("check_doc_counts", _SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_MOD = _load()


# ---------------------------------------------------------------------------
# The freshness check
# ---------------------------------------------------------------------------


def _run_main(
    monkeypatch: pytest.MonkeyPatch,
    argv: list[str],
    *,
    stale: list[str] | None = None,
    mode: tuple[bool, str] | Exception | None = None,
) -> tuple[int, list[Path]]:
    """`main()` with render_status's answer and the release-mode answer
    stubbed; returns the exit code and the roots the freshness check was
    asked about."""
    asked: list[Path] = []

    def stale_blocks(root: Path) -> list[str]:
        asked.append(root)
        return list(stale or [])

    monkeypatch.setattr(
        _MOD, "_render_status",
        lambda: types.SimpleNamespace(stale_blocks=stale_blocks),
    )
    if mode is not None:
        def release_mode_for(base: str, root: Path) -> tuple[bool, str]:
            if isinstance(mode, Exception):
                raise mode
            return mode

        monkeypatch.setattr(_MOD, "release_mode_for", release_mode_for)
    monkeypatch.setattr(sys, "argv", ["check_doc_counts.py", *argv])
    monkeypatch.setattr(sys, "path", list(sys.path))
    return _MOD.main(), asked


class TestTheFreshnessCheck:
    def test_release_mode_fails_on_a_stale_status(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        stale = "TESTING.md: the generated `test-files` block is not current"
        code, asked = _run_main(monkeypatch, ["--release"], stale=[stale])
        assert code == 1
        assert asked == [_SCRIPT.resolve().parent.parent]
        assert stale in capsys.readouterr().err

    def test_release_mode_passes_a_current_status(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        code, asked = _run_main(monkeypatch, ["--release"], stale=[])
        assert (code, len(asked)) == (0, 1)

    def test_the_default_mode_reads_no_count(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """A fix PR's run: a status that has fallen behind the tree is not
        an error between releases, so the check is not even asked."""
        code, asked = _run_main(monkeypatch, [], stale=["stale"])
        assert (code, asked) == (0, [])
        assert "--release" in capsys.readouterr().out

    def test_it_reaches_the_real_generator(self, tmp_path: Path) -> None:
        """No stubs: the script loads render_status.py from beside itself
        and returns its answer — here, that a document without the
        markers cannot be checked."""
        (tmp_path / "TESTING.md").write_text("# Testing\n", encoding="utf-8")
        (error,) = _MOD.stale_status(tmp_path)
        assert "render_status:begin status" in error


class TestMainActsOnTheReleaseModeAnswer:
    """`--release-if-version-raised` turns the freshness check on exactly
    when the version rose, and a base it cannot read fails the script."""

    def test_a_raised_version_checks_the_status(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        code, asked = _run_main(
            monkeypatch, ["--release-if-version-raised", "main"],
            stale=["stale"], mode=(True, "0.2.0 -> 0.2.1"),
        )
        assert (code, len(asked)) == (1, 1)

    def test_an_unraised_version_does_not(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        code, asked = _run_main(
            monkeypatch, ["--release-if-version-raised", "main"],
            stale=["stale"], mode=(False, "0.2.1 -> 0.2.1"),
        )
        assert (code, asked) == (0, [])

    def test_an_explicit_release_flag_is_not_turned_off(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        code, asked = _run_main(
            monkeypatch, ["--release", "--release-if-version-raised", "main"],
            stale=[], mode=(False, "0.2.1 -> 0.2.1"),
        )
        assert (code, len(asked)) == (0, 1)

    def test_an_unreadable_base_exits_one_before_any_check(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        code, asked = _run_main(
            monkeypatch, ["--release-if-version-raised", "no-such-ref"],
            mode=_MOD.ReleaseModeError("cannot read pyproject.toml"),
        )
        assert (code, asked) == (1, [])


class TestPrintReleaseMode:
    """`--print-release-mode BASE` is ci.yml's plan job asking whether
    `[project].version` rose against BASE, for the test matrix to read as a
    step output.  It prints one `release=` line and checks no document; a
    base it cannot read fails the step rather than answering either way."""

    def _main(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
        answer: tuple[bool, str] | Exception,
    ) -> tuple[int, str, str]:
        code, asked = _run_main(
            monkeypatch, ["--print-release-mode", "b" * 40], mode=answer,
        )
        assert asked == [], "the plan's question checks no document"
        out, err = capsys.readouterr()
        return code, out, err

    def test_a_raised_version_prints_true(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        code, out, err = self._main(monkeypatch, capsys, (True, "0.2.0 -> 0.2.1"))
        assert (code, out) == (0, "release=true\n")
        assert "0.2.0 -> 0.2.1" in err

    def test_an_unraised_version_prints_false(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        code, out, err = self._main(monkeypatch, capsys, (False, "0.2.1 -> 0.2.1"))
        assert (code, out) == (0, "release=false\n")
        assert "0.2.1 -> 0.2.1" in err

    def test_an_unreadable_base_prints_no_answer_and_fails(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        code, out, err = self._main(
            monkeypatch, capsys, _MOD.ReleaseModeError("cannot read pyproject.toml"),
        )
        assert (code, out) == (1, "")
        assert "cannot read pyproject.toml" in err


# ---------------------------------------------------------------------------
# Release mode keys on the version bump (#1536)
# ---------------------------------------------------------------------------


def _pyproject(version: str) -> str:
    return f'[project]\nname = "veralang"\nversion = "{version}"\n'


class TestVersionRaised:
    @pytest.mark.parametrize(
        ("base", "head", "raised"),
        [
            ("0.1.13", "0.2.0", True),
            ("0.2.0", "0.2.1", True),
            ("0.2.9", "0.2.10", True),  # numeric, not lexicographic
            ("0.2.0", "0.2.0", False),
            ("0.2.1", "0.2.0", False),
            ("0.10.0", "0.9.9", False),
        ],
    )
    def test_it_compares_versions_numerically(
        self, base: str, head: str, raised: bool
    ) -> None:
        assert _MOD.version_raised(_pyproject(base), _pyproject(head)) is raised

    def test_an_unreadable_version_is_an_error_not_a_default(self) -> None:
        with pytest.raises(ValueError):
            _MOD.version_raised("[project]\nname = 'x'\n", _pyproject("0.2.0"))


def _scrubbed_env() -> dict[str, str]:
    """The inherited environment without `GIT_*`: under a hook those name
    the outer repository, and a temporary repository's git must not reach
    it."""
    return {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}


def _repo_with_versions(tmp_path: Path, *versions: str) -> tuple[Path, list[str]]:
    """A repository with one commit per version, on a branch `main` that
    is also published as `origin/main`, as a CI checkout has it.  Returns
    the root and the commits' SHAs, oldest first."""
    repo = tmp_path / "repo"
    repo.mkdir()
    env = _scrubbed_env()

    def git(*args: str) -> str:
        return subprocess.run(
            ["git", *args], cwd=repo, env=env, check=True,
            capture_output=True, text=True, encoding="utf-8",
        ).stdout.strip()

    git("init", "-q", "-b", "main")
    git("config", "user.email", "t@example.invalid")
    git("config", "user.name", "t")
    shas = []
    for version in versions:
        (repo / "pyproject.toml").write_text(_pyproject(version), encoding="utf-8")
        git("add", "pyproject.toml")
        git("commit", "-q", "--allow-empty", "-m", version)
        shas.append(git("rev-parse", "HEAD"))
    git("update-ref", "refs/remotes/origin/main", shas[0])
    return repo, shas


class TestReleaseModeFor:
    def test_a_pull_request_that_raises_the_version_is_the_release(
        self, tmp_path: Path
    ) -> None:
        """CI passes a pull request's base branch by name; it is read as
        `origin/<base>`, the ref a CI checkout carries."""
        repo, _ = _repo_with_versions(tmp_path, "0.1.13", "0.2.0")
        release, why = _MOD.release_mode_for("main", repo)
        assert release is True
        assert "0.1.13 -> 0.2.0" in why

    def test_a_pull_request_that_keeps_the_version_is_not(
        self, tmp_path: Path
    ) -> None:
        """The case the base-branch trigger got wrong: a fix PR into `main`."""
        repo, _ = _repo_with_versions(tmp_path, "0.2.0", "0.2.0")
        release, _why = _MOD.release_mode_for("main", repo)
        assert release is False

    def test_a_push_compares_against_the_commit_before_it(
        self, tmp_path: Path
    ) -> None:
        repo, shas = _repo_with_versions(tmp_path, "0.1.13", "0.2.0", "0.2.0")
        # The release merge raised the version against the commit before it.
        subprocess.run(
            ["git", "checkout", "-q", shas[1]], cwd=repo, env=_scrubbed_env(),
            check=True, capture_output=True,
        )
        assert _MOD.release_mode_for(shas[0], repo)[0] is True
        # The next push to main did not.
        subprocess.run(
            ["git", "checkout", "-q", shas[2]], cwd=repo, env=_scrubbed_env(),
            check=True, capture_output=True,
        )
        assert _MOD.release_mode_for(shas[1], repo)[0] is False

    def test_a_new_branch_has_no_previous_commit(self, tmp_path: Path) -> None:
        """A push that creates a branch reports an all-zero `before`."""
        repo, _ = _repo_with_versions(tmp_path, "0.2.0")
        release, why = _MOD.release_mode_for("0" * 40, repo)
        assert release is False
        assert "new branch" in why

    @pytest.mark.parametrize("base", ["", "no-such-ref"])
    def test_an_unreadable_base_fails_closed(
        self, tmp_path: Path, base: str
    ) -> None:
        """A base that names nothing must not be read as "not a release":
        that would silently skip the release checks on the release PR."""
        repo, _ = _repo_with_versions(tmp_path, "0.2.0")
        with pytest.raises(_MOD.ReleaseModeError):
            _MOD.release_mode_for(base, repo)

    def test_the_outer_repository_is_not_consulted(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Under a hook, `GIT_DIR` names the outer repository; the script's
        own git must read the tree it was given."""
        repo, _ = _repo_with_versions(tmp_path, "0.1.13", "0.2.0")
        monkeypatch.setenv("GIT_DIR", str(tmp_path / "elsewhere" / ".git"))
        assert _MOD.release_mode_for("main", repo)[0] is True

    def test_a_git_that_hangs_fails_closed(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A `git show` that never returns is bounded, and an expired one is
        an unreadable base — `ReleaseModeError` — rather than a hung CI job
        (PR #1606 review)."""
        repo, _ = _repo_with_versions(tmp_path, "0.1.13", "0.2.0")
        budgets: list[object] = []

        def hang(cmd: Any, **kwargs: Any) -> Any:
            budgets.append(kwargs.get("timeout"))
            raise subprocess.TimeoutExpired(cmd, kwargs.get("timeout") or 0)

        monkeypatch.setattr(_MOD.subprocess, "run", hang)
        with pytest.raises(_MOD.ReleaseModeError):
            _MOD.release_mode_for("main", repo)
        # Both candidates were tried, each under a finite budget.
        assert len(budgets) == 2
        assert all(isinstance(b, (int, float)) and b > 0 for b in budgets)


# ---------------------------------------------------------------------------
# The script measures the checkout it lives in
# ---------------------------------------------------------------------------


def _make_fake_checkout(root: Path, marker: str) -> None:
    (root / "vera").mkdir(parents=True)
    (root / "vera" / "__init__.py").write_text(
        f'MARKER = "{marker}"\n', encoding="utf-8")
    (root / "scripts").mkdir()


class TestCrossCheckoutImportIsolation:
    """render_status.py imports `vera` in process; a script that inserts its
    own root at `sys.path[0]` before that import measures its own checkout,
    whatever `PYTHONPATH` or an editable install says."""

    def test_root_insertion_wins_over_a_stale_pythonpath(
        self, tmp_path: Path,
    ) -> None:
        _make_fake_checkout(tmp_path / "checkout_a", "A")
        _make_fake_checkout(tmp_path / "checkout_b", "B")
        probe = tmp_path / "checkout_a" / "scripts" / "probe.py"
        probe.write_text(
            "import sys\n"
            "from pathlib import Path\n"
            "root = Path(__file__).resolve().parent.parent\n"
            "sys.path.insert(0, str(root))\n"
            "import vera\n"
            "print(vera.MARKER)\n",
            encoding="utf-8",
        )
        env = dict(os.environ)
        env["PYTHONPATH"] = str(tmp_path / "checkout_b")
        result = subprocess.run(
            [sys.executable, str(probe)],
            capture_output=True, text=True, encoding="utf-8",
            env=env, check=False,
        )
        assert result.stdout.strip() == "A", result.stderr

    def test_without_the_fix_a_stale_pythonpath_wins(
        self, tmp_path: Path,
    ) -> None:
        """The negative control: without the insertion the same setup
        resolves the other checkout's package."""
        _make_fake_checkout(tmp_path / "checkout_a", "A")
        _make_fake_checkout(tmp_path / "checkout_b", "B")
        probe = tmp_path / "checkout_a" / "scripts" / "probe_unfixed.py"
        probe.write_text("import vera\nprint(vera.MARKER)\n", encoding="utf-8")
        env = dict(os.environ)
        env["PYTHONPATH"] = str(tmp_path / "checkout_b")
        result = subprocess.run(
            [sys.executable, str(probe)],
            capture_output=True, text=True, encoding="utf-8",
            env=env, check=False,
        )
        assert result.stdout.strip() == "B", result.stderr

    def test_main_inserts_root_before_the_freshness_check(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """`main()` puts its root first on `sys.path` before it asks
        render_status anything, so the generator's `vera` imports resolve
        to this checkout."""
        seen: list[str] = []

        def stale_blocks(root: Path) -> list[str]:
            seen.append(sys.path[0])
            return []

        monkeypatch.setattr(
            _MOD, "_render_status",
            lambda: types.SimpleNamespace(stale_blocks=stale_blocks),
        )
        monkeypatch.setattr(sys, "argv", ["check_doc_counts.py", "--release"])
        monkeypatch.setattr(sys, "path", ["/somewhere/else", *sys.path])
        assert _MOD.main() == 0
        assert seen == [str(_SCRIPT.resolve().parent.parent)]


# ---------------------------------------------------------------------------
# KNOWN_ISSUES.md's Bugs table against the tracker (--check-bug-issues)
# ---------------------------------------------------------------------------

_BUGS_DESCRIPTION = (
    "Defects in shipped compiler, runtime, or tooling behaviour — this"
    " table matches the issue tracker's open `bug`-labelled issues"
    " one-to-one."
)


def _bugs_section(body: str) -> str:
    """A KNOWN_ISSUES.md whose `## Bugs` section holds `body`."""
    return (
        f"# Known Issues\n\n## Bugs\n\n{_BUGS_DESCRIPTION}\n\n{body}\n\n"
        "## Limitations\n\n| Limitation | Issue |\n|-----------|-------|\n"
        "| Something missing. |"
        " [#900](https://github.com/aallan/vera/issues/900) |\n"
    )


def _bugs(*rows: str) -> str:
    body = "\n".join(rows)
    return _bugs_section(f"| Bug | Issue |\n|-----|-------|\n{body}")


def _row(number: int, text: str = "Something is wrong.") -> str:
    url = f"https://github.com/aallan/vera/issues/{number}"
    return f"| {text} | [#{number}]({url}) |"


class TestBugRows:
    """The reader the release-time parity check stands on."""

    def test_the_shipped_table_parses(self) -> None:
        text = (_SCRIPT.parent.parent / "KNOWN_ISSUES.md").read_text(encoding="utf-8")
        rows = _MOD.bug_rows(text)
        assert not isinstance(rows, str), rows
        section = re.search(r"^## Bugs[ \t]*$(.*?)(?=^## )", text, re.M | re.S)
        assert section is not None
        table = [
            line for line in section.group(1).splitlines()
            if line.startswith("|") and not set(line) <= set("|- ")
        ][1:]  # drop the header row
        assert len(rows) == len(table)

    def test_only_the_issue_column_is_read(self) -> None:
        """A row's prose cross-links other issues; only its last cell is
        its tracker, and a `|` in the prose cannot shift it."""
        text = _bugs(
            _row(101, "Like [#7](https://github.com/aallan/vera/issues/7), the `|>` is wrong."),
            _row(102),
        )
        assert _MOD.bug_rows(text) == [101, 102]

    @pytest.mark.parametrize(
        ("body", "reason"),
        [
            ("| Bug | Issue |\n|-----|-------|\n| No tracker. | none |", "exactly one"),
            ("| Bug | Issue |\n|-----|-------|\n"
             "| Mislinked. | [#101](https://github.com/aallan/vera/issues/202) |", "exactly one"),
            ("| Bug | Issue |\n|-----|-------|", "does not end with"),
            ("Some prose but no table and no marker.", "does not end with"),
            ("No known bugs.\n\nBut there is one.", "does not END with it"),
            (f"No known bugs.\n\n| Bug | Issue |\n|-----|-------|\n{_row(101)}", "both"),
        ],
        ids=["no link", "mislinked", "emptied table", "no marker",
             "text after the marker", "marker and table"],
    )
    def test_an_unreadable_table_is_a_reason(self, body: str, reason: str) -> None:
        read = _MOD.bug_rows(_bugs_section(body))
        assert isinstance(read, str) and reason in read, read

    def test_the_zero_form_is_read_beside_the_description(self) -> None:
        assert _MOD.bug_rows(_bugs_section("No known bugs.")) == []

    def test_a_renamed_heading_is_a_reason(self) -> None:
        assert isinstance(_MOD.bug_rows(_bugs(_row(101)).replace("## Bugs", "## Open")), str)


class TestBugIssueParity:
    def test_a_matching_pair_of_sets_is_clean(self) -> None:
        assert _MOD.check_bug_issue_parity([101, 102], [102, 101]) == []

    def test_an_open_bug_issue_with_no_row_is_reported(self) -> None:
        errors = _MOD.check_bug_issue_parity([101], [101, 102])
        assert len(errors) == 1 and "#102" in errors[0]

    def test_a_row_whose_issue_is_not_an_open_bug_is_reported(self) -> None:
        errors = _MOD.check_bug_issue_parity([101, 103], [101])
        assert len(errors) == 1 and "#103" in errors[0]

    def test_no_open_bug_issues_is_an_error_not_a_skip(self) -> None:
        """An empty fetch beside rows is a failed query, not a clean
        bill of health."""
        errors = _MOD.check_bug_issue_parity([101], [])
        assert [e for e in errors if "not found" in e]

    def test_both_sides_at_zero_agree(self) -> None:
        """#1401 — the burndown's success state, checked against the
        tracker rather than exempted from it."""
        assert _MOD.check_bug_issue_parity([], []) == []

    def test_zero_rows_against_a_non_empty_tracker_is_an_error(self) -> None:
        errors = _MOD.check_bug_issue_parity([], [1317])
        assert len(errors) == 1 and "#1317" in errors[0]


class TestCheckBugIssues:
    """`--check-bug-issues` as the release PR runs it: the file read, the
    tracker queried (stubbed here), and every way the two disagree
    reported."""

    def _check(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
        text: str, tracker: list[int] | Exception,
    ) -> list[str]:
        (tmp_path / "KNOWN_ISSUES.md").write_text(text, encoding="utf-8")

        def open_bug_issues() -> list[int]:
            if isinstance(tracker, Exception):
                raise tracker
            return tracker

        monkeypatch.setattr(_MOD, "open_bug_issues", open_bug_issues)
        errors: list[str] = _MOD.check_bug_issues(tmp_path)
        return errors

    def test_an_agreeing_table_is_clean(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        assert self._check(tmp_path, monkeypatch, _bugs(_row(1), _row(2)), [2, 1]) == []

    def test_two_rows_for_one_issue_are_an_error(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """One-to-one: a duplicate row is not two bugs, though the sets agree."""
        errors = self._check(
            tmp_path, monkeypatch, _bugs(_row(1), _row(1, "Again.")), [1],
        )
        assert errors == ["KNOWN_ISSUES.md: issue #1 has a Bugs row twice"]

    def test_an_unreadable_table_is_an_error_not_a_skip(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        errors = self._check(
            tmp_path, monkeypatch, _bugs_section("| Bug | Issue |\n|-----|-------|"), [1],
        )
        assert len(errors) == 1 and "cannot be read" in errors[0]

    def test_a_failed_query_is_an_error(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        errors = self._check(
            tmp_path, monkeypatch, _bugs(_row(1)), _MOD.BugQueryError("offline"),
        )
        assert errors == ["KNOWN_ISSUES.md: offline"]

    def test_the_tracker_is_asked_only_when_the_flag_says_so(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A run without `--check-bug-issues` makes no network call."""
        def no_network() -> list[int]:
            raise AssertionError("the GitHub API was queried")

        monkeypatch.setattr(_MOD, "open_bug_issues", no_network)
        for argv in ([], ["--release"]):
            code, _asked = _run_main(monkeypatch, argv, stale=[])
            assert code == 0, argv
